from app.common.domain.exceptions import CustomException


class PostNotFoundError(CustomException):
    pass
